import {
  AndroidMessages,
  Caprine,
  Chat,
  Code,
  Default,
  Emacs,
  Figma,
  GoogleChrome,
  Firefox,
  Spotify,
  Terminal,
  Music,
  Safari,
  SequelPro,
  Skype,
  Slack,
  Zeplin,
  Bias,
  Piano,
  Calculator,
  Dashlane,
  Movies,
  Agenda,
  Discord,
  Preview,
  Unity,
  Video
} from './components/Icons.jsx';

export const appIcons = {
'Android Messages': AndroidMessages,
  Caprine: Caprine,
  Code: Code,
  Default: Default,
  Figma: Figma,
  'Dashlane': Dashlane,
  Discord: Discord,
  Firefox: Firefox,
  Spotify: Spotify,
  Preview: Preview,
  Calculator: Calculator,
  Emacs: Emacs,
  Alacritty: Terminal,
  iTerm2: Terminal,
  Unity: Unity,
  Agenda: Agenda,
  'Popcorn-Time': Movies,
  'BIAS FX': Bias,
  IINA: Video,
  Live: Piano,
  'Google Chrome': GoogleChrome,
  Station: Chat,
  Safari: Safari,
  Music: Music,
  'Sequel Pro': SequelPro,
  Skype: Skype,
  Slack: Slack,
  Zeplin: Zeplin
};
